services:
  tapestryviewer:
    build: ./
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${GOOGLE_PRIVATE_KEY}
      GOOGLE_SHEETS_ID: ${GOOGLE_SHEETS_ID}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: production
    ports:
      - 3000:3000
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: tapestry
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tapestry
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080